// <auto-generated />
using System;
using CRM.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251007124252_AddIsAdminToAgente")]
    partial class AddIsAdminToAgente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agents.Domain.Aggregates.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Setores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Setor responsável por questões financeiras e boletos.",
                            Nome = "Financeiro",
                            Version = new Guid("f6b3a2a8-8e6a-4b2a-8b8d-9b8e1f0c3b1a")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Setor responsável por vendas e novas oportunidades.",
                            Nome = "Comercial",
                            Version = new Guid("d4a3b4d5-6e7f-8a9b-0c1d-2e3f4a5b6c7d")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Setor responsável pela administração geral",
                            Nome = "Administracao",
                            Version = new Guid("d4a3b4d5-6e7f-8a9b-0c1d-2e3f4a5b6c7a")
                        });
                });

            modelBuilder.Entity("Agents.Domain.Entities.Agente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SetorId");

                    b.ToTable("Agentes", (string)null);
                });

            modelBuilder.Entity("Contacts.Domain.Entities.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.Property<string>("WaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.HasIndex("WaId")
                        .IsUnique();

                    b.ToTable("Contatos", (string)null);
                });

            modelBuilder.Entity("Contacts.Domain.Entities.HistoricoStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContatoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId");

                    b.ToTable("HistoricoStatus");
                });

            modelBuilder.Entity("Conversations.Domain.Entities.Atendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("BotStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataFinalizacao");

                    b.Property<Guid?>("SetorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.ToTable("Atendimentos", (string)null);
                });

            modelBuilder.Entity("Conversations.Domain.Entities.Conversa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContatoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContatoNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TagsId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalSessoesIniciadas")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TagsId");

                    b.ToTable("Conversas", (string)null);
                });

            modelBuilder.Entity("Conversations.Domain.Entities.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnexoUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("MessageId")
                        .HasColumnType("text")
                        .HasColumnName("MessageId");

                    b.Property<string>("ReacaoMensagem")
                        .HasColumnType("text");

                    b.Property<string>("Texto")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.ToTable("Mensagens", (string)null);
                });

            modelBuilder.Entity("Tags.Domain.Entities.Tags", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Templates.Domain.Entities.MessageTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MotivoRejeicao")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MessageTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000001"),
                            Body = "Olá {{1}}, Tudo bem?",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Template de boas-vindas para novos usuários.",
                            Language = "pt_BR",
                            Name = "template",
                            Status = 1,
                            Version = new Guid("f6b3a2a8-8e6a-4b2a-8b8d-9b8e1f0c3b1a")
                        });
                });

            modelBuilder.Entity("Agents.Domain.Entities.Agente", b =>
                {
                    b.HasOne("Agents.Domain.Aggregates.Setor", null)
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Contacts.Domain.Entities.HistoricoStatus", b =>
                {
                    b.HasOne("Contacts.Domain.Entities.Contato", null)
                        .WithMany("HistoricoStatus")
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Conversations.Domain.Entities.Atendimento", b =>
                {
                    b.HasOne("Conversations.Domain.Entities.Conversa", null)
                        .WithMany()
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Conversations.Domain.ValueObjects.Avaliacao", "Avaliacao", b1 =>
                        {
                            b1.Property<Guid>("AtendimentoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Comentario")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("AvaliacaoComentario");

                            b1.Property<int>("Nota")
                                .HasColumnType("integer")
                                .HasColumnName("AvaliacaoNota");

                            b1.HasKey("AtendimentoId");

                            b1.ToTable("Atendimentos");

                            b1.WithOwner()
                                .HasForeignKey("AtendimentoId");
                        });

                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("Conversations.Domain.Entities.Conversa", b =>
                {
                    b.HasOne("Tags.Domain.Entities.Tags", "Tag")
                        .WithMany()
                        .HasForeignKey("TagsId");

                    b.OwnsOne("Conversations.Domain.ValueObjects.SessaoWhatsapp", "SessaoAtiva", b1 =>
                        {
                            b1.Property<Guid>("ConversaId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("DataFim")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("SessaoFim");

                            b1.Property<DateTime>("DataInicio")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("SessaoInicio");

                            b1.HasKey("ConversaId");

                            b1.ToTable("Conversas");

                            b1.WithOwner()
                                .HasForeignKey("ConversaId");
                        });

                    b.Navigation("SessaoAtiva");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Conversations.Domain.Entities.Mensagem", b =>
                {
                    b.HasOne("Conversations.Domain.Entities.Conversa", null)
                        .WithMany("Mensagens")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Conversations.Domain.ValueObjects.Remetente", "Remetente", b1 =>
                        {
                            b1.Property<Guid>("MensagemId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("AgenteId")
                                .HasColumnType("uuid")
                                .HasColumnName("RemetenteAgenteId");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("RemetenteTipo");

                            b1.HasKey("MensagemId");

                            b1.ToTable("Mensagens");

                            b1.WithOwner()
                                .HasForeignKey("MensagemId");
                        });

                    b.Navigation("Remetente")
                        .IsRequired();
                });

            modelBuilder.Entity("Tags.Domain.Entities.Tags", b =>
                {
                    b.HasOne("Agents.Domain.Entities.Agente", null)
                        .WithMany()
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Contacts.Domain.Entities.Contato", b =>
                {
                    b.Navigation("HistoricoStatus");
                });

            modelBuilder.Entity("Conversations.Domain.Entities.Conversa", b =>
                {
                    b.Navigation("Mensagens");
                });
#pragma warning restore 612, 618
        }
    }
}
