// <auto-generated />
using System;
using CRM.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250702124538_AddAutoAtendimento")]
    partial class AddAutoAtendimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agents.Domain.Aggregates.Agente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetorIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Agentes", (string)null);
                });

            modelBuilder.Entity("Agents.Domain.Aggregates.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Setores", (string)null);
                });

            modelBuilder.Entity("Contacts.Domain.Aggregates.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("Contatos", (string)null);
                });

            modelBuilder.Entity("Contacts.Domain.Entities.HistoricoStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContatoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId");

                    b.ToTable("HistoricoStatus");
                });

            modelBuilder.Entity("Conversations.Domain.Aggregates.Conversa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<int>("BotStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("ContatoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SetorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Conversas", (string)null);
                });

            modelBuilder.Entity("Conversations.Domain.Entities.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnexoUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("ConversaId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageId")
                        .HasColumnType("text")
                        .HasColumnName("MessageId");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.ToTable("Mensagens", (string)null);
                });

            modelBuilder.Entity("Agents.Domain.Aggregates.Agente", b =>
                {
                    b.OwnsOne("CargaDeTrabalho", "CargaDeTrabalho", b1 =>
                        {
                            b1.Property<Guid>("AgenteId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Valor")
                                .HasColumnType("integer")
                                .HasColumnName("CargaDeTrabalho");

                            b1.HasKey("AgenteId");

                            b1.ToTable("Agentes");

                            b1.WithOwner()
                                .HasForeignKey("AgenteId");
                        });

                    b.Navigation("CargaDeTrabalho")
                        .IsRequired();
                });

            modelBuilder.Entity("Contacts.Domain.Aggregates.Contato", b =>
                {
                    b.OwnsMany("Contacts.Domain.ValueObjects.Tag", "Tags", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ContatoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("ContatoId");

                            b1.ToTable("ContatoTags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContatoId");
                        });

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Contacts.Domain.Entities.HistoricoStatus", b =>
                {
                    b.HasOne("Contacts.Domain.Aggregates.Contato", null)
                        .WithMany("HistoricoStatus")
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Conversations.Domain.Entities.Mensagem", b =>
                {
                    b.HasOne("Conversations.Domain.Aggregates.Conversa", null)
                        .WithMany("Mensagens")
                        .HasForeignKey("ConversaId");

                    b.OwnsOne("Conversations.Domain.ValueObjects.Remetente", "Remetente", b1 =>
                        {
                            b1.Property<Guid>("MensagemId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("AgenteId")
                                .HasColumnType("uuid")
                                .HasColumnName("RemetenteAgenteId");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("RemetenteTipo");

                            b1.HasKey("MensagemId");

                            b1.ToTable("Mensagens");

                            b1.WithOwner()
                                .HasForeignKey("MensagemId");
                        });

                    b.Navigation("Remetente")
                        .IsRequired();
                });

            modelBuilder.Entity("Contacts.Domain.Aggregates.Contato", b =>
                {
                    b.Navigation("HistoricoStatus");
                });

            modelBuilder.Entity("Conversations.Domain.Aggregates.Conversa", b =>
                {
                    b.Navigation("Mensagens");
                });
#pragma warning restore 612, 618
        }
    }
}
