trigger:
  branches:
    include:
      - main

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

stages:
  - stage: Docker
    displayName: Docker Container
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: "Build and Push Image"
            inputs:
              containerRegistry: "Docker Hub Wegen"
              repository: "wegen983/crmapi"
              command: "buildAndPush"
              dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              tags: |
                latest
                $(tag)
